# Generated by scripts/sea/generate-formula.mjs — do not edit by hand.
# The `formula` job in .github/workflows/release-binaries.yml regenerates
# this file for every release and opens a PR with the result.
class Acpx < Formula
  desc "Headless CLI client for the Agent Client Protocol (ACP)"
  homepage "https://github.com/openclaw/acpx"

  # Two install paths, resolved per platform:
  #
  # Platforms with a published asset get a self-contained Node
  # single-executable: the bundle and a V8 startup snapshot injected into an
  # official Node binary, with no runtime dependency on a system Node and
  # ~50ms startup versus ~77ms for the npm package. The snapshot is
  # architecture-specific, so each asset is built on a native runner by
  # release-binaries.yml; Homebrew's own node has SEA support compiled out
  # and cannot build them from source.
  #
  # Every other platform installs the npm package below with Homebrew's
  # node — same code, ordinary module resolution instead of a snapshot.
  #
  # Binary assets carry build-provenance and SBOM attestations, and releases
  # are immutable, so each sha256 pins bytes that cannot be replaced
  # upstream. See docs/verifying-releases.md.
  url "https://registry.npmjs.org/acpx/-/acpx-0.12.1.tgz"
  version "0.12.1"
  sha256 "c759e05bfc628a99da32e04e384272a49ff34ada454ce87550d2a6ac234e58de"
  license "MIT"

  on_macos do
    depends_on "node"
  end

  on_linux do
    depends_on "node"
  end

  def install
    npm_layout = (buildpath/"package.json").file?
    binary_layout = (buildpath/"acpx").file? && (buildpath/"acpx").executable?

    odie "Ambiguous acpx release layout" if npm_layout && binary_layout

    if binary_layout
      bin.install "acpx"
    elsif npm_layout
      system "npm", "install", *std_npm_args
      bin.install_symlink Dir["#{libexec}/bin/*"]
    else
      odie "Unknown acpx release layout"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/acpx --version")

    # On binary platforms this must answer without a system Node on PATH —
    # that is the property that justifies shipping a ~122MB executable.
    assert_match "Usage", shell_output("#{bin}/acpx --help")
  end
end
