#!/usr/bin/env node
/**
 * Renders Formula/acpx.rb from a release's checksum manifest.
 *
 * The formula serves two install paths and this script is the only writer of
 * both, so they cannot drift apart:
 *
 *  - Binary: platforms with a published single-executable asset get a
 *    url/sha256 block pointing at the immutable release tarball.
 *  - Node: every other platform falls back to the npm registry tarball and a
 *    Homebrew `node` dependency, installed with std_npm_args.
 *
 * Run by the `formula` job in .github/workflows/release-binaries.yml after the
 * release is published. Runnable locally the same way:
 *
 *   node scripts/sea/generate-formula.mjs \
 *     --version 0.12.0 --npm-sha256 <sha> --sums SHA256SUMS
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 2) {
    const key = argv[i];
    const value = argv[i + 1];
    if (!/^--[a-z0-9-]+$/.test(key) || value === undefined) {
      throw new Error(`Malformed arguments near ${key ?? "<end>"}.`);
    }
    args[key.slice(2)] = value;
  }
  return args;
}

const args = parseArgs(process.argv.slice(2));
const version = args.version ?? "";
const npmSha = args["npm-sha256"] ?? "";
const sumsPath = args.sums ?? "";
const outPath = args.out ?? path.join(repoRoot, "Formula", "acpx.rb");

if (!/^\d+\.\d+\.\d+$/.test(version)) {
  throw new Error(`--version must be X.Y.Z; received "${version}".`);
}
if (!/^[0-9a-f]{64}$/.test(npmSha)) {
  throw new Error(`--npm-sha256 must be 64 hex characters; received "${npmSha}".`);
}

// The four slots Homebrew can address with on_macos/on_linux × on_arm/on_intel.
// A manifest naming any other target fails the run: silently skipping it would
// publish a formula that pretends the platform does not exist.
const SLOTS = ["darwin-arm64", "darwin-x64", "linux-arm64", "linux-x64"];

const shaByTarget = new Map();
for (const line of fs.readFileSync(sumsPath, "utf8").split("\n")) {
  if (line.trim() === "") continue;
  const match = /^([0-9a-f]{64})\s+(\S+)$/.exec(line.trim());
  if (!match) {
    throw new Error(`Unparseable checksum line: "${line}".`);
  }
  const [, sha, name] = match;
  if (!name.endsWith(".tar.gz")) continue;
  const asset = new RegExp(`^acpx-(\\d+\\.\\d+\\.\\d+)-([a-z0-9-]+)\\.tar\\.gz$`).exec(name);
  if (!asset) {
    throw new Error(`Tarball "${name}" does not match acpx-<version>-<target>.tar.gz.`);
  }
  if (asset[1] !== version) {
    throw new Error(`Tarball "${name}" is for version ${asset[1]}, expected ${version}.`);
  }
  if (!SLOTS.includes(asset[2])) {
    throw new Error(`Tarball "${name}" names unknown target "${asset[2]}".`);
  }
  shaByTarget.set(asset[2], sha);
}

if (shaByTarget.size === 0) {
  throw new Error(`${sumsPath} lists no acpx tarballs; refusing to emit a binary-free formula.`);
}

const releaseBase = `https://github.com/artagon/acpx/releases/download/v${version}`;

/** One platform slot: a binary url/sha256 pair, or the node fallback. */
function slotLines(target, indent) {
  const sha = shaByTarget.get(target);
  if (sha === undefined) {
    return [`${indent}depends_on "node"`];
  }
  return [
    `${indent}url "${releaseBase}/acpx-${version}-${target}.tar.gz"`,
    `${indent}sha256 "${sha}"`,
  ];
}

/** on_macos / on_linux block, collapsing when both arches take the same path. */
function osBlock(os, armTarget, intelTarget) {
  const bothMissing = !shaByTarget.has(armTarget) && !shaByTarget.has(intelTarget);
  if (bothMissing) {
    return [`  on_${os} do`, `    depends_on "node"`, "  end"];
  }
  return [
    `  on_${os} do`,
    "    on_arm do",
    ...slotLines(armTarget, "      "),
    "    end",
    "    on_intel do",
    ...slotLines(intelTarget, "      "),
    "    end",
    "  end",
  ];
}

const formula = [
  "# Generated by scripts/sea/generate-formula.mjs — do not edit by hand.",
  "# The `formula` job in .github/workflows/release-binaries.yml regenerates",
  "# this file for every release and opens a PR with the result.",
  "class Acpx < Formula",
  '  desc "Headless CLI client for the Agent Client Protocol (ACP)"',
  '  homepage "https://github.com/artagon/acpx"',
  "",
  "  # Two install paths, resolved per platform:",
  "  #",
  "  # Platforms with a published asset get a self-contained Node",
  "  # single-executable: the bundle and a V8 startup snapshot injected into an",
  "  # official Node binary, with no runtime dependency on a system Node and",
  "  # ~50ms startup versus ~77ms for the npm package. The snapshot is",
  "  # architecture-specific, so each asset is built on a native runner by",
  "  # release-binaries.yml; Homebrew's own node has SEA support compiled out",
  "  # and cannot build them from source.",
  "  #",
  "  # Every other platform installs the npm package below with Homebrew's",
  "  # node — same code, ordinary module resolution instead of a snapshot.",
  "  #",
  "  # Binary assets carry build-provenance and SBOM attestations, and releases",
  "  # are immutable, so each sha256 pins bytes that cannot be replaced",
  "  # upstream. See docs/verifying-releases.md.",
  `  url "https://registry.npmjs.org/acpx/-/acpx-${version}.tgz"`,
  `  version "${version}"`,
  `  sha256 "${npmSha}"`,
  '  license "MIT"',
  "",
  ...osBlock("macos", "darwin-arm64", "darwin-x64"),
  "",
  ...osBlock("linux", "linux-arm64", "linux-x64"),
  "",
  "  def install",
  "    if (buildpath/\"acpx\").exist?",
  "      bin.install \"acpx\"",
  "    else",
  "      system \"npm\", \"install\", *std_npm_args",
  "      bin.install_symlink Dir[\"#{libexec}/bin/*\"]",
  "    end",
  "  end",
  "",
  "  test do",
  "    assert_match version.to_s, shell_output(\"#{bin}/acpx --version\")",
  "",
  "    # On binary platforms this must answer without a system Node on PATH —",
  "    # that is the property that justifies shipping a ~122MB executable.",
  "    assert_match \"Usage\", shell_output(\"#{bin}/acpx --help\")",
  "  end",
  "end",
  "",
].join("\n");

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, formula);

const targets = [...shaByTarget.keys()].sort().join(", ");
process.stdout.write(`Wrote ${outPath} for v${version} (binary: ${targets}; npm fallback elsewhere)\n`);
